title: "Global Dengue: Case Database by Country (1995-2024)"
description: "Database of confirmed and reported dengue cases in 31 countries across Latin America, South Asia, and Southeast Asia, with time series from 1995 to 20"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/global-dengue-case-database-by-country-1995-2024"
